//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\BinShred.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBinShredListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class BinShredBaseListener : IBinShredListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplate([NotNull] BinShredParser.TemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplate([NotNull] BinShredParser.TemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.templateEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateEntry([NotNull] BinShredParser.TemplateEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.templateEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateEntry([NotNull] BinShredParser.TemplateEntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.parseRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParseRule([NotNull] BinShredParser.ParseRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.parseRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParseRule([NotNull] BinShredParser.ParseRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.ruleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleBody([NotNull] BinShredParser.RuleBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.ruleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleBody([NotNull] BinShredParser.RuleBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] BinShredParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] BinShredParser.PropertyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.lookupTableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLookupTableName([NotNull] BinShredParser.LookupTableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.lookupTableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLookupTableName([NotNull] BinShredParser.LookupTableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.ruleOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleOptions([NotNull] BinShredParser.RuleOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.ruleOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleOptions([NotNull] BinShredParser.RuleOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.byteOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterByteOption([NotNull] BinShredParser.ByteOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.byteOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitByteOption([NotNull] BinShredParser.ByteOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.sizeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeReference([NotNull] BinShredParser.SizeReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.sizeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeReference([NotNull] BinShredParser.SizeReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.byteFormat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterByteFormat([NotNull] BinShredParser.ByteFormatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.byteFormat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitByteFormat([NotNull] BinShredParser.ByteFormatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.lookupTable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLookupTable([NotNull] BinShredParser.LookupTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.lookupTable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLookupTable([NotNull] BinShredParser.LookupTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.lookupTableEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLookupTableEntry([NotNull] BinShredParser.LookupTableEntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.lookupTableEntry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLookupTableEntry([NotNull] BinShredParser.LookupTableEntryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.lookupTableEntryKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLookupTableEntryKey([NotNull] BinShredParser.LookupTableEntryKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.lookupTableEntryKey"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLookupTableEntryKey([NotNull] BinShredParser.LookupTableEntryKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BinShredParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] BinShredParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BinShredParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] BinShredParser.LabelContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
